### PR TITLE
Update for Swift 3.0.1

### PR DESCRIPTION
**Pull request by elland**
This is a shallow update to 3.0.1. It doesn't try to reimplement any protocol conformance, it's mostly syntactical changes and formatting.

😄

### CODE REVIEW

**Comment by Sjors** [comment]
Thanks!
I noticed you renamed the playground and commented everything out. Why is that? It seems to work if you rename the two occurrences of `hexStringValue`.

**Comment by elland** [comment]
@Sjors It would give me an error when trying to build the iOS framework. 🤔 There are still a few points I'd like to clean up, mostly because of the 32bit v 64bit thing. 👍

**Comment by Sjors** [comment]
It's been forever since I worked on this code, but I think the Playground should only work for the OSX build. Does it completely break the iOs build?

**Comment by elland** [comment]
@Sjors No, Xcode just complains that it can't find the module and stops the building process. Could be something specific to Xcode configuration, I didn't much look into it. I can also just as well uncomment it and remove it from the iOS target, as I should have from the start. 😄

**Comment by Sjors** [comment]
That sounds like a good approach.

Just let me know when you've finished the other changes you have in mind and then I'll merge it.

**Comment by elland** [comment]
Thanks. 👍

**Comment by zackshapiro** [comment]
Any updates on this? Just found this and it'll be really helpful for some of my crypto work

**Comment by elland** [comment]
After so long, might be worth looking into doing it Swift4 style, with the new number protocols?

**Comment by zackshapiro** [comment]
I need this for a crypto project I'm doing. I can take a look.

@Elland Should I pull this branch to get started?

**Comment by Sjors** [comment]
@zackshapiro you really shouldn't use this. It's highly experimental. However, I will have some time to merge stuff over the next few weeks, so PR's are welcome.

**Comment by zackshapiro** [comment]
@Sjors Thanks Sjors. 

I pulled @Elland's branch and was hoping to update it to Swift 4. I've never done bit-level programming before so I'm probably not the best person at this point in time to be submitting PRs. Looking for an implementation that works that I can ideally just drop into my project and go

Learning as I go though

**Comment by elland** [comment]
@zackshapiro if you're doing crypto, you're probably safer using `NSDecimalNumber`, is what we use for [Toshi](https://github.com/toshiapp/toshi-ios-client).

**Comment by zackshapiro** [comment]
@Elland I was looking through the Toshi repo yesterday, the old one that points to the new repo address and saw you were using this library. Didn't know you were connected in any way.

I'm just trying to create 256 bit hashes for seeds and key pairs. Do you think `NSDecimalNumber` can achieve that for me?

**Comment by elland** [comment]
@zackshapiro even better, check out https://github.com/bakkenbaeck/EtherealCereal 👍

**Comment by zackshapiro** [comment]
Thanks @Elland

**Pull request closed without merging**
